layout_spectrum: 0.7260448054876179
typography_spectrum: 0.6862426465377212
color:
  brandStrength: 0.9901213010307401
  lightness: 0.9136456486303359
  saturation: 0.1160228590015322
  rhythmicContrast: 0.9580646662507206
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Taomoon's Workshop
